CREATE DATABASE IF NOT EXISTS `unit6_test_app` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `unit6_test_app`;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    img_big VARCHAR(255) NOT NULL,
    img_small VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
